---
# Enter in the path to the block storage database volume
mnt_dir: /var/mnt/dbvolume

# Enter in the owner and group for permission assignment of the mount_dir
mnt_owner: root
mnt_group: root

# default device name
block_device: /dev/sda

mongodb_net_bindip: "{{ hostvars['mongodb-1'].priv_ip_addr }}"