---

- name: Set up custom directory for mount
  file: path={{ mnt_dir }} state=directory

- name: Format block device to ext4 
  filesystem: fstype=ext4 dev={{ block_device }}

- name: Mount new block storage file system
  mount: state=mounted fstype=ext4 name={{ mnt_dir }} src={{ block_device }} opts="discard,defaults"

- name: Set up system user
  user: name={{ mnt_owner }} state=present

- name: Change directory ownership and permissions of the mount volume
  file: path={{ mnt_dir }} state=directory owner={{ mnt_owner }} group={{ mnt_group }}


