# clone the repository

- name: clone node boilerplate app from public git repository 
  git:
    repo: "{{ git_repo_url }}"
    dest: "/usr/local/{{ project_folder_name }}"
    version: "{{ git_repo_version }}"
    force: yes
    accept_hostkey: yes
  become: no

- name: npm install based on package.json in /usr/local/{{ project_folder_name }} 
  become: yes
  command: "npm install"
  args:
    chdir: /usr/local/{{ project_folder_name }}  

- name: fix npm dependency bug with node-saas package 
  become: yes
  command: "npm rebuild node-sass"
  args:
    chdir: /usr/local/{{ project_folder_name }}  

- name: install pm2 globally 
  become: yes
  command: "npm install -g pm2"
  args:
    chdir: /usr/local/{{ project_folder_name }}  

#- debug:
#    msg: "Public IP of mongoDB server: {{ hostvars['mongodb-1'].ansible_host}}"

#- debug:
#    msg: "Private IP of mongoDB server: {{ hostvars['mongodb-1'].ansible_eth0.ipv4_secondaries[0].broadcast}}"

- debug: 
    msg: "exporting variable MONGODB_URI=mongodb://{{ hostvars['mongodb-1'].priv_ip_addr }}:27017/test"

- name: starting App server on {{ hostvars['nodejs-1'].ansible_host}}:8080
  #- name: Starting app with MONGODB_URI=mongodb://{{ hostvars['mongodb-1'].ansible_eth0.ipv4_secondaries[0].broadcast}}:27017/test
  become: no
  environment:
    MONGODB_URI: mongodb://{{ hostvars['mongodb-1'].priv_ip_addr }}:27017/test
    NODE_ENV: production
  command: pm2 start app.js --name node-app
  args:
    chdir: /usr/local/{{ project_folder_name }}

- debug:
    msg: "Playbook completed.  Open your browser to the NGINX proxy at: http://{{ hostvars['nodejs-1'].ansible_host}}"



